[package]
name = "dissemination"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.16", features = ["derive"] }
csv = "1.3.0"
rand = "0.8.5"
strum = "0.26.3"
strum_macros = "0.26.4"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
