name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  mixnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        working-directory: simlib
        run: cargo build -v
      - name: Unit tests
        working-directory: simlib
        run: cargo test -v
